[versions]
project = "0.1.1"
java = "21"
gjson = "2.13.2"
junit = "6.0.2"
jetbrains-annotations = "24.1.0"
apache-mina = "2.2.5"
bouncycastle = "1.83"

[libraries]
junit-launch = {module = "org.junit.platform:junit-platform-launcher", version.ref = "junit"}
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }


apache-mina = { module = "org.apache.mina:mina-core", version.ref = "apache-mina" }
bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }


gjson = { module = "com.google.code.gson:gson", version.ref = "gjson" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }


